# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: [ubuntu-latest, macos-latest, windows-latest]

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i 
    - run: npm run build
    - name: Download all workflow run artifacts
      uses: actions/upload-artifact@v2
      with:
        path: dist
      
        
      
      
